'use strict';
const assert=require('node:assert/strict');
const {calculate,defaults,validate}=require('../web/src/sandbox.js');
let passed=0;
function test(name,fn){fn();passed++;console.log('PASS',name);}
const run=overrides=>calculate({...defaults,...overrides});
test('24 monthly rows',()=>assert.equal(run({}).rows.length,24));
test('baseline closes at 180000',()=>assert.equal(run({}).ending_cash,180000));
test('no input mutation',()=>{const d={...defaults};calculate(d);assert.deepEqual(d,defaults);});
test('one-off enters once',()=>{const r=run({oneoff:900000});assert.equal(r.ending_cash,1080000);assert.equal(r.rows.filter(x=>x.oneoff>0).length,1);});
test('business sale stops recurring income in event month',()=>{const r=run({eventKind:'business-sale',oneoff:900000});assert.equal(r.rows[4].variable,5000);assert.equal(r.rows[5].variable,0);assert.equal(r.ending_cash,985000);});
test('selling in month 1 stops all variable income',()=>assert.equal(run({eventKind:'business-sale',eventMonth:1,oneoff:900000}).ending_cash,960000));
test('selling in month 24 stops one payment',()=>assert.equal(run({eventKind:'business-sale',eventMonth:24,oneoff:900000}).ending_cash,1075000));
test('salary remains after sale',()=>assert.equal(run({eventKind:'business-sale'}).rows[10].stable,8000));
test('income shock starts in month 1',()=>assert.equal(run({drop:50}).rows[0].variable,2500));
test('first negative is an unfunded gap not credit',()=>{const r=run({startCash:0,drop:100});assert.equal(r.first_gap_month,1);assert.equal(r.ending_cash,-60000);});
test('zero balance is not negative',()=>assert.equal(run({startCash:0,expenses:13000}).first_gap_month,null));
test('expense escalation occurs at month 13',()=>{const r=run({expenseGrowth:10});assert.equal(r.rows[11].expenses,10500);assert.equal(r.rows[12].expenses,11550);assert.equal(r.ending_cash,167400);});
test('cents are handled exactly',()=>assert.equal(run({startCash:0.1,stableIncome:0.2,businessIncome:0,expenses:0.1}).ending_cash,2.5));
test('identity every row',()=>run({eventKind:'business-sale',oneoff:199900,expenseGrowth:2.5}).rows.forEach(r=>assert.equal(Math.round((r.opening+r.stable+r.variable+r.oneoff-r.expenses)*100),Math.round(r.closing*100))));
for(const invalid of [NaN,Infinity,-1,1e10,'',null,true,{},'abc'])test('reject bad starting cash '+String(invalid),()=>assert.throws(()=>run({startCash:invalid})));
test('reject impossible probability-like shock',()=>assert.throws(()=>run({drop:101})));
test('reject fractional date',()=>assert.throws(()=>run({eventMonth:1.5})));
test('reject date zero',()=>assert.throws(()=>run({eventMonth:0})));
test('reject beyond horizon',()=>assert.throws(()=>run({eventMonth:25})));
test('reject unknown event',()=>assert.throws(()=>run({eventKind:'execute-trade'})));
test('reject fractional cents',()=>assert.throws(()=>run({expenses:12.345})));
test('safe bounds',()=>assert.doesNotThrow(()=>run({startCash:1e9,oneoff:1e9,stableIncome:1e8,expenseGrowth:50})));
test('explicit numeric strings',()=>assert.equal(validate({...defaults,stableIncome:'8000.00'}).stableIncome,8000));
console.log(`\n${passed} browser arithmetic tests passed.`);
